### ISSUE TITLE
use of undeclared crate or module arbitrary

### ISSUE THREAD

**Issue by gyzerok** [rust-fuzz/cargo-fuzz#307]
Hello there!

I am trying to use `cargo-fuzz` in my project and st up everything like it is described in the book. However for some reason running fuzz tests fails with `use of undeclared crate or module arbitrary`

Here is my Cargo.toml
```toml
[package]
name = "retro-api-fuzz"
version = "0.0.0"
authors = ["Automatically generated"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }
uuid = { version = "=1.1.1", features = ["serde", "v4", "arbitrary"] }

[dependencies.retro-api]
path = ".."
features = ["arbitrary"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "remove_ticket"
path = "fuzz_targets/remove_ticket.rs"
test = false
doc = false

```
and here is my fuzz target code
```rust
#![no_main]
use libfuzzer_sys::{arbitrary::Arbitrary, fuzz_target};

use uuid::Uuid;

use retro_api::experiment::BoardAggregate;

#[derive(Arbitrary, Debug)]
struct Input {
    board_aggregate: BoardAggregate,
    ticket_id: Uuid,
}

fuzz_target!(|input: Input| {
    let Input {
        board_aggregate,
        ticket_id,
    } = input;

    let event = board_aggregate.remove_ticket(ticket_id);

    if let Ok(event) = event {
        assert!(board_aggregate.replay(event).is_ok());
    }
});
```

This setup produces following error
```
error[E0433]: failed to resolve: use of undeclared crate or module `arbitrary`
 --> fuzz_targets/remove_ticket.rs:9:10
  |
9 | #[derive(Arbitrary, Debug)]
  |          ^^^^^^^^^ use of undeclared crate or module `arbitrary`
  |
  = note: this error originates in the derive macro `Arbitrary` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Is it a bug or am I missing something here?
