### ISSUE TITLE
`cargo fuzz init` fails with `edition.workspace = true`

### ISSUE THREAD

**Issue by mauricelam** [rust-fuzz/cargo-fuzz#333]
When running `cargo fuzz init` on a workspace, where the member crate's Cargo.toml has `edition.workspace = true`, the command fails.

`Cargo.toml`:
```toml
[worksapce]
members = [
  "member",
]

[workspace.package]
edition = "2021"
```

`member/Cargo.toml`:
```toml
[package]
name = "member"
version = "0.1.0"
edition.workspace = true
```

```sh
$ cd member
$ cargo fuzz init
Error: /path/to/project/member/Cargo.toml (package.edition) is malformed
```

`edition.workspace` is supported by cargo itself per https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table. If I change `edition.workspace = true` back to `edition = "2021"`, the init command runs successfully.
