### ISSUE TITLE
Consider using a workspace instead of a fully separate crate

### ISSUE THREAD

**Issue by jyn514** [rust-fuzz/cargo-fuzz#345]
Right now, `cargo fuzz init` generates the following Cargo.toml:
```toml
[package]
name = "example-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.example]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
```
In particular, this puts all the fuzz targets in a separate workspace. I am not sure why that decision was made - it prevents reusing the build cache between the fuzzer and the rest of the code. It would be nice if they shared a workspace and therefore a cache.

I do see that this configures `profile.release`, so to avoid interfering with existing configs it could use a new `profile.fuzzing` or something like that.
