### ISSUE TITLE
Add proper tests for CI

### ISSUE THREAD

**Issue by Manishearth** [rust-fuzz/cargo-fuzz#69]
It should cd to a test crate directory, that contains a single function which panics on an input of size 6 or something, then fuzz init, edit the fuzz target to call this function, run the fuzz target, and ensure a crashfile is produced of the correct length.

**Comment by Manishearth** [comment]
@ner0x652 want to work on this?

**Comment by ner0x652** [comment]
@Manishearth If it doesn't need beyond intermediate level of Rust knowledge, then YES! (tomorrow after work)

**Comment by Manishearth** [comment]
It would mostly be a shell script that does the steps above. We'd probably check in the test crate to be fuzzed.

**Comment by Manishearth** [comment]
Willing to help if you need any.

**Comment by ner0x652** [comment]
Good! :+1:

**Comment by ner0x652** [comment]
@Manishearth left 2 links on IRC, in case you didn't see them here is what I wrote:
This is `deploy.sh` in `scripts` folder:
```bash
# This script leaves in /scripts, go to parent, this should be needed only locally
cd ..
mkdir etc && cd etc 
cargo new testcrate
cd testcrate

testcrate_lib_source="
pub fn test_func(slice: &[u8]) {
    if slice.len() == 7 {
        panic!(\"I'm afraid of number 7\");
    }
}
"
echo "$testcrate_lib_source" > src/lib.rs

cargo build
cargo-fuzz init

fuzzer_script_source="
#![no_main]
extern crate libfuzzer_sys;
extern crate testcrate;

use testcrate::test_func;

#[export_name=\"rust_fuzzer_test_input\"]
pub extern fn go(data: &[u8]) {
    test_func(data);
}
"
echo "$fuzzer_script_source" > fuzz/fuzzers/fuzzer_script_1.rs

cargo-fuzz run fuzzer_script_1
```

And this is the new travis.yml
```yaml
language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux

matrix:
  fast_finish: true

notifications:
  email: false

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
```

Is this (close to) what you were thinking of?
